sonar.projectKey=Algorithmiq_src-method
sonar.organization=algorithmiq

sonar.projectName=src-method
sonar.python.coverage.reportPaths=coverage-*.xml
sonar.python.version=3.11, 3.12, 3.13, 3.14
sonar.sources=src
sonar.tests=tests
sonar.verbose=true

sonar.exclusions=\
  src/src_method/_version.py
